repos:
  - repo: local
    hooks:
    - id: update-last-modified-header
      name: Update Last-Modified Field in Header
      entry: python .pre-commit-hooks/update-last-modified-header.py
      language: python

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
    - id: poetry-install

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb', '2048']

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
